apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-developer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-developer-backend
  template:
    metadata:
      labels:
        app: e2e-developer-backend
    spec:
      containers:
        - name: e2e-developer-backend
          image: e2e-developer-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-developer-backend
spec:
  type: NodePort
  selector:
    app: e2e-developer-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
